name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - ubuntu-20.04
        sourcemod-version:
          - 1.11-dev
        include:
          - os: ubuntu-latest
            target-archs: x86
            compiler_cc: clang
            compiler_cxx: clang++

          - os: windows-latest
            target-archs: x86
            compiler_cc: msvc

          - os: ubuntu-20.04
            target-archs: x86
            compiler_cc: clang-8
            compiler_cxx: clang++-8

    steps:
      - name: Install ${{ matrix.os }} packages
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-multilib g++-multilib libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 linux-libc-dev \
            linux-libc-dev:i386 lib32z1-dev ${{ matrix.compiler_cc }}

      - name: Select compiler
        if: runner.os == 'Linux'
        run: |
          echo "CC=${{ matrix.compiler_cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler_cxx }}" >> $GITHUB_ENV
          ${{ matrix.compiler_cc }} --version
          ${{ matrix.compiler_cxx }} --version

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
            python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: extension

      - name: Checkout SourceMod
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sourcemod-version }}
          path: sourcemod
          submodules: recursive

      - name: Checkout AMBuild
        uses: actions/checkout@v3
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          echo ${{ github.run_number }}
          mkdir build && cd build
          python ../configure.py --enable-optimize --targets=${{ matrix.target-archs }}
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: extension/build/package


  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - ubuntu-20.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Package
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          7z a jansson-${version}.${{ github.run_number }}-${{ matrix.os }}.zip ./${{ matrix.os }}/*

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true
